### ISSUE TITLE
Link e logo da posição quebrada

### ISSUE THREAD

**Issue by pfgianoto** [elisei/theme-full-checkout#4]
Ola pessoal! tudo bem?
Como podem ver no print ao instalar o Theme Full Checkout (Checkout Identification Step, Input Masking, Advanced Fields, Field Sort in Checkout, Advanced Street Address e AutoComplete Address Br todos da O2TI) ele ficou meio bugado, mudando o local da logo e a URL da logo com parte da chamada PHP quando passo o mouse em cima da logo a URL fica assim: /checkout/getLogoUrl()

https://prnt.sc/cqXAyyI9RGC3

Rodando Magento 2.4.1 com Tema Porto.

**Comment by elisei** [comment]
Olá @pfgianoto 

Você deve olhar para o seu tema e comprar as alterações que ele faz no checkout (em relação ao Luma) e então criar no seu tema pasta O2TI/ThemeFullCheckout/layout/checkout_onepage_index.xml onde irá remover essa personalização e em web/source/_module.less você editará o css...

Eu tinha a personalização para esse tema mas na bagunça aqui não consegui achar senão lhe enviava, mas lembro que foi um trabalho bem pequeno para deixa-lo exatamente como o checkout fica no luma!

**Comment by pfgianoto** [comment]
Obrigado Bruno! Realmente no Luma ele fica muito show! Vou tentar fazer a customização por aqui, se por acaso achar ai ai voce me manda.
Uma duvida, passando o mouse em cima da logo a URL da loja fica errada ex: enderecodaloja.com.br/checkout/getLogoUrl()

Mesmo no tema Luma isso acontece.
