### ISSUE TITLE
Social Login URI Error. 

### ISSUE THREAD

**Issue by ItaloEduardoo** [elisei/theme-full-checkout#5]
### Request for Facebook and Google OAuth Redirect URI Configuration

I'm setting up social login for both Facebook and Google on my website and encountering redirect errors. The error message displayed is:

> "URL Blocked: This redirect failed because the URL is not whitelisted in the app’s OAuth settings. Make sure Client and Web OAuth Login are on and add all app domains as Valid OAuth Redirect URIs."

#### Expected Behavior
The social login for Facebook and Google should redirect correctly to the authorized URLs on the configured domain.

#### Actual Behavior
Redirection errors occur due to missing or incorrect URLs in the **Valid OAuth Redirect URIs** configuration for both Facebook and Google.

### Request

Could you please provide the exact URLs to add to the **Valid OAuth Redirect URIs** field in both the Facebook Developer Console and Google Cloud Console?

#### Domain Details
- Current site domain: `https://prospin.com.br/`
- Social login page URL: `https://prospin.com.br/customer/account/create/`

### Steps to Reproduce
1. Go to the login page at https://prospin.com.br/customer/account/create/
2. Click on the social login buttons for Facebook or Google.
3. See the error regarding unauthorized redirect URLs.

---

If possible, please share the correct **Valid OAuth Redirect URIs** for both Facebook and Google or provide additional guidance to ensure social login functions properly on the configured domain.

I have already added the domain and subpages to the Facebook app, and when testing via API, it works correctly. However, in the production environment, the error still occurs.

![image](https://github.com/user-attachments/assets/1e268e23-e53b-43d1-96b0-27a346081f47)

**Comment by elisei** [comment]
Oi @ItaloEduardoo 

Você as acha aqui:
https://github.com/elisei/social-login/wiki

**Comment by ItaloEduardoo** [comment]
Olá @elisei 
Fiz conforme o video informa, porém o facebook continua apresentando erro na url de direcionamento
![image](https://github.com/user-attachments/assets/c5b2dd7a-b547-4efc-b864-34778ccf50d1)

**Comment by elisei** [comment]
Está em produção isso?

Em qua., 30 de out. de 2024, 15:21, ItaloEduardoo ***@***.***>
escreveu:

**Comment by ItaloEduardoo** [comment]
@elisei 
Sim o APP está publicado e verificado, vou ativar o botão no site para você ver o erro se possível.
https://www.prospin.com.br/customer/account/login/

**Comment by elisei** [comment]
Entra aqui por favor!
https://meet.google.com/nvd-gmxi-ucj

**Comment by elisei** [comment]
Fechado após atendimento!
O cliente definiu a url com sem "www" no entanto o site usa "www" por isso havia erro de redirecionamento.
